#######################################
# Website
#######################################


lang: fr
from: markdown+emoji
filters:
  - iconify
project:
  type: website
  render:
  - index.qmd
  - resources.qmd
  - cours/index.qmd
  - slides/index.qmd
  - slides/ACP.qmd
  - slides/SVD.qmd
  - slides/presentation.qmd
  - td/1_ACP/TD.qmd
  - tp/index.qmd
  - tp/markdown.qmd
  - tp/quarto.qmd



website:
  bread-crumbs: false
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "Statistical Exploration"
  site-url: https://bcharlier.github.io/KMAK7AC1/
  repo-url: https://github.com/bcharlier/KMAK7AC1
  repo-actions: [source, issue]
  search:
    location: navbar
    type: textbox
  navbar:
    title: KMAK7AC1
    background: primary
    search: true
    left:
      - sidebar:Cours
      - sidebar:Slides
      - sidebar:TD
      - sidebar:TP
      - sidebar:Quarto
    right:
      - text: "{{<iconify simple-icons:moodle title='Moodle'>}}"
        href: https://moodle.utoulouse.fr/
        aria-label: Moodle
      - text: "{{< iconify simple-icons:github title='GitHub'>}}"
        href: https://github.com/bcharlier/KMAK7AC1
        aria-label: GitHub
  sidebar:

    - id: Cours
      collapse-level: 3
      contents: 
        - cours/index.qmd

    - id: Slides
      collapse-level: 3
      contents:
        - slides/presentation.qmd
        - slides/SVD.qmd
        - slides/ACP.qmd

    - id: TD
      collapse-level: 3
      contents:
        - td/1_ACP/TD.qmd
    
    - id: TP
      collapse-level: 3
      contents:
        - tp/index.qmd
    
    - id: Quarto
      collapse-level: 2
      contents:
        - tp/markdown.qmd
        - tp/quarto.qmd


format:
  html:
    theme: [lux, custom.scss]
    css: table.css

    html-math-method: katex
    number-sections: false
    toc-depth: 3
    code-fold: false
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    highlight-style: github
    fig-responsive: true
    fig.align: center
    reference-location: margin
    citation-location: margin
    from: markdown+emoji

    #toc-location: right
    #toc: true

execute:
  freeze: auto
  cache: false