---
title: "Statistique Exploratoire et Apprentissage non supervisé"
subtitle: "KMAK7AC1"
---

::: {.course-banner}
## Objectifs

Présenter les concepts de base des méthodes exploratoires multidimensionnelles, qui permettent de décrire, synthétiser et/ou partitionner l’information contenue dans de grands tableaux de données.

Nous aborderons d’abord les méthodes de réduction de dimension linéaire, puis les méthodes de classification non supervisée, ou clustering.
:::


## Prérequis et compétences

Prérequis

- Notions d'algèbre linéaire (réduction d'endomorphismes)
- Statistique descriptive

Compétences acquises

- Savoir utiliser les outils selon le contexte d’application.
- Mise en œuvre avec les outils modernes de la science des données en R et/ou Python.
- Interprétation des résultats obtenus.

## Organisation générale

- 2h * 12 séances de Cours/TD
- 2h * 3 séances de TP sur R et/ou Python en demi groupe
- Supports de cours en ligne et Moodle
- Évaluation
    - 1 Contrôle continu: évaluation sur table 1h
    - 1 Contrôle terminal: évaluation sur table 2h
    - Bonus: *Pull Request* pour améliorer ce cours jusquà 1pt sur la note finale


## Séances en détail

| Date | Activité | Thème |
|---|---|---|
| 07/09 | CM/TD | ACP |
| 09/09 | CM/TD | ACP |
| 10/09 | CM/TD | ACP |
| 21/09 | CM/TD | ACP/AFC |
| 23/09 | CM/TD | AFC |
| 25/09 | CM/TD | AFC/ACM |
| 28/09 | CM/TD | ACM |
| 30/09 | CM/TD | AFM |
| 05/10 | CM/TD | Apprentissage non supervisé |
| 07/10 | CM/TD | Apprentissage non supervisé |
| 07/10 | TP1 * 2 | |
| 12/10 | CM/TD | Apprentissage non supervisé |
| 14/10 | TP2 * 2 | |
| 21/10 | CM/TD | Apprentissage non supervisé |
| 21/10 | TP3 * 2 | |
